version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ..:/go/src/github.com/worming004/fullsystemtest/productservice
      - /var/run/docker.sock:/var/run/docker-host.sock 
    command: sleep infinity 
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=aStrong!Password741
      - MONGO_INITDB_DATABASE=productsdb
