openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /products:
    get:
      responses:
        '200':
          description: get all products
          content:
             application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
    post:
      requestBody:
        description: post a new product
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: product to submit
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/Id'
  /products/{id}:
    get:
      parameters:
        - name: id
          in: path
          description: ProductId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: get unique product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    delete:
      parameters:
        - name: id
          in: path
          description: ProductId
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: deleted
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        price:
          type: integer
      required:
        - name
        - price
    Id:
      type: object
      properties:
        id: 
          type: integer
      required:
        - id