/*
 * API Title
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API. 
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// ProductsGet - 
func (s *DefaultApiService) ProductsGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update ProductsGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, InlineResponse200{}) or use other options such as http.Ok ...
	//return Response(200, InlineResponse200{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ProductsGet method not implemented")
}

// ProductsIdDelete - 
func (s *DefaultApiService) ProductsIdDelete(ctx context.Context, id int32) (ImplResponse, error) {
	// TODO - update ProductsIdDelete with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ProductsIdDelete method not implemented")
}

// ProductsIdGet - 
func (s *DefaultApiService) ProductsIdGet(ctx context.Context, id int32) (ImplResponse, error) {
	// TODO - update ProductsIdGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Product{}) or use other options such as http.Ok ...
	//return Response(200, Product{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ProductsIdGet method not implemented")
}

// ProductsPost - 
func (s *DefaultApiService) ProductsPost(ctx context.Context, product Product) (ImplResponse, error) {
	// TODO - update ProductsPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, Id{}) or use other options such as http.Ok ...
	//return Response(201, Id{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ProductsPost method not implemented")
}

